name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.JdvkhMvUN2vVW4ejGGfcHL3aPE }}" | docker login -u "${{ secrets.ghaidafarsi }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghaidafarsi/evalution:latest .
        docker push ghaidafarsi/evalution:latest
